services:
    _defaults:
        autowire: true
        autoconfigure: true

    numero2\PerviewBundle\Cron\ImportAdvertisementsCron:
        arguments:
            - '@database_connection'
            - '@logger'

    numero2_perview.import.perview:
        class: numero2\PerviewBundle\Import\PerviewImport
        public: true
        arguments:
            - '@database_connection'
            - '@request_stack'
            - '@contao.routing.scope_matcher'
            - '@logger'
            - '@contao.translation.translator'
            - '@http_client'
